version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache-container
    ports:
      - "8000:8000"
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "
      chown -R www-data:www-data /var/www/html/5026221096 &&
      chmod -R 775 /var/www/html/5026221096/storage /var/www/html/5026221096/bootstrap/cache &&
      exec apache2-foreground
      "

  db:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: superSecretPassword
      MYSQL_DATABASE: myDatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
